---
version: 2
before:
  hooks:
    - go mod download
builds:
  -
    id: protolint
    env:
      - CGO_ENABLED=0
    main: ./cmd/protolint/main.go
    binary: protolint
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm
        goarm: 6
      - goos: windows
        goarch: arm
        goarm: 7
    ldflags:
      - -s -w -X github.com/maramkhaledn/protolint/internal/cmd.version={{.Version}} -X github.com/maramkhaledn/protolint/internal/cmd.revision={{.ShortCommit}}  # yamllint disable-line rule:line-length
  -
    id: protoc-gen-protolint
    env:
      - CGO_ENABLED=0
    main: ./cmd/protoc-gen-protolint/main.go
    binary: protoc-gen-protolint
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm
        goarm: 6
      - goos: windows
        goarch: arm
        goarm: 7
    ldflags:
      - -s -w -X github.com/maramkhaledn/protolint/internal/cmd/protocgenprotolint.version={{.Version}} -X github.com/maramkhaledn/protolint/internal/cmd/protocgenprotolint.revision={{.ShortCommit}}  # yamllint disable-line rule:line-length
archives:
checksum:
  name_template: checksums.txt
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  -
    name: protolint
    repository:
      owner: maramkhaledn
      name: homebrew-protolint
    commit_author:
      name: goreleaserbot
      email: marakhaled@noon.com
    directory: Formula
    description: Pluggable tool to enforce Protocol Buffer style and conventions
    homepage: https://github.com/maramkhaledn/protolint
    test: |
      system "#{bin}/protolint", "version"
      system "#{bin}/protoc-gen-protolint", "version"
    install: |
      bin.install "protolint"
      bin.install "protoc-gen-protolint"
      prefix.install "LICENSE"
docker_manifests:
  # https://goreleaser.com/customization/docker_manifest/
  - name_template: maramkhaledn/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - maramkhaledn/{{ .ProjectName }}:{{ .Tag }}-amd64
      - maramkhaledn/{{ .ProjectName }}:{{ .Tag }}-arm64v8
      - maramkhaledn/{{ .ProjectName }}:{{ .Tag }}-armv6
      - maramkhaledn/{{ .ProjectName }}:{{ .Tag }}-armv7
  - name_template: maramkhaledn/{{ .ProjectName }}:latest
    image_templates:
      - maramkhaledn/{{ .ProjectName }}:latest-amd64
      - maramkhaledn/{{ .ProjectName }}:latest-arm64v8
      - maramkhaledn/{{ .ProjectName }}:latest-armv6
      - maramkhaledn/{{ .ProjectName }}:latest-armv7
dockers:
  # https://goreleaser.com/customization/docker/
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - maramkhaledn/{{ .ProjectName }}:{{ .Tag }}-amd64
      - maramkhaledn/{{ .ProjectName }}:latest-amd64
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.title={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - maramkhaledn/{{ .ProjectName }}:{{ .Tag }}-arm64v8
      - maramkhaledn/{{ .ProjectName }}:latest-arm64v8
    build_flag_templates:
      - --platform=linux/arm64/v8
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.title={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
  - use: buildx
    goos: linux
    goarch: arm
    goarm: 6
    image_templates:
      - maramkhaledn/{{ .ProjectName }}:{{ .Tag }}-armv6
      - maramkhaledn/{{ .ProjectName }}:latest-armv6
    build_flag_templates:
      - --platform=linux/arm/v6
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.title={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
  - use: buildx
    goos: linux
    goarch: arm
    goarm: 7
    image_templates:
      - maramkhaledn/{{ .ProjectName }}:{{ .Tag }}-armv7
      - maramkhaledn/{{ .ProjectName }}:latest-armv7
    build_flag_templates:
      - --platform=linux/arm/v7
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.title={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
